Welcome/Controllers/DepartmentController.cs
using Demo.BLL.Interfaces;
using Demo.DAl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Welcome.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DepartmentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task< IActionResult> Index()
        {
            IEnumerable<Department> departments =await _unitOfWork.DepartmentRepo.GetAll();
            return View(departments);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
               await _unitOfWork.DepartmentRepo.Add(department);
               await _unitOfWork.Save();
                TempData["Message"] = "Department is created Successfuly";
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }
        public async Task< IActionResult> Details(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Department department =await _unitOfWork.DepartmentRepo.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }
        public async Task< IActionResult> Edit(int id )
        {
            Department department=await _unitOfWork.DepartmentRepo.GetById(id);
            return View(department);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Edit([FromRoute]int id,Department department)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.DepartmentRepo.Update(department);
                   await _unitOfWork.Save();
                    return RedirectToAction(nameof(Index));
                }catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(department);
           
        }
        public async Task< IActionResult> Delete(int id)
        {
           Department department=await _unitOfWork.DepartmentRepo.GetById(id);
            if(department == null)
            {
                return BadRequest();
            }
            return View(department);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Delete([FromRoute]int id,Department department)
        {
            try
            {
                _unitOfWork.DepartmentRepo.Delete(department);
               await _unitOfWork.Save();
                return RedirectToAction(nameof(Index));

            }catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(department);

            }
        }

        public IActionResult EmployeesCount(int id)
        {
            _unitOfWork.DepartmentRepo.GetDepartmentEmployees(id);
            return View();


        }


    }
}

Welcome/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Welcome.Helpers;
using Welcome.ViewModels;

namespace Welcome.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
       
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        public EmployeeController(IUnitOfWork unitOfWork,IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;


        }

        public async Task< IActionResult> Index()
        {
            IEnumerable<Employee> employees =await _unitOfWork.EmployeeRepo.GetAll();
            var mappedEmployee = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
            return View(mappedEmployee);
        }
        public async Task< IActionResult> Create( )
        {  
            ViewData["Departments"]=await _unitOfWork.DepartmentRepo.GetAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Create(EmployeeViewModel employeeVm)
        {
            if (ModelState.IsValid)
            {
                
                employeeVm.ImageName = DocumentSettinga.UploadFile(employeeVm.Image, "Images");
                var mappedEmp=_mapper.Map<EmployeeViewModel, Employee>(employeeVm);
               await _unitOfWork.EmployeeRepo.Add(mappedEmp);
               await _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Departments"] =await _unitOfWork.DepartmentRepo.GetAll();
            return View(employeeVm);
        }
        public async Task< IActionResult> Details(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Employee employee =await _unitOfWork.EmployeeRepo.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            var mappedEmployee=_mapper.Map<Employee,EmployeeViewModel>(employee);
            return View(mappedEmployee);
        }
        public async Task< IActionResult> Edit(int id)
        {
            ViewBag.Departments =await _unitOfWork.DepartmentRepo.GetAll();
            Employee employee =await _unitOfWork.EmployeeRepo.GetById(id);
            var mappedEmp = _mapper.Map<Employee,EmployeeViewModel>(employee);
            return View(mappedEmp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employeeVm.ImageName = DocumentSettinga.UploadFile(employeeVm.Image, "Images");
                    var mappedEmp =_mapper.Map<EmployeeViewModel, Employee>(employeeVm);
                    _unitOfWork.EmployeeRepo.Update(mappedEmp);
                   await _unitOfWork.Save();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(employeeVm);

        }
        public async Task< IActionResult> Delete(int id)
        {
            Employee employee =await _unitOfWork.EmployeeRepo.GetById(id);
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(employee);
            if (employee == null)
            {
                return BadRequest();
            }
            return View(mappedEmp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Delete([FromRoute] int id, EmployeeViewModel employeeVm)
        {
            try
            {
                var mappedEmployee = _mapper.Map<EmployeeViewModel,Employee> (employeeVm);
                _unitOfWork.EmployeeRepo.Delete(mappedEmployee);
               await _unitOfWork.Save();
                DocumentSettinga.DeleteFile(mappedEmployee.ImageName, "Images");
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                var mappedEmp=_mapper.Map<EmployeeViewModel,Employee>(employeeVm);
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(mappedEmp);

            }
        }
        public async Task<IActionResult> ChangeState(int id)
        {
            Employee employee=await _unitOfWork.EmployeeRepo.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            else
            {
                employee.IsActive=!employee.IsActive;
                _unitOfWork.Save();
                return Ok();
            }

        }
    }
}

Welcome/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAl.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Welcome.ViewModels;

namespace Welcome.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager,IMapper mapper)
        {
            _roleManager = roleManager;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.Select(R => new RoleViewModel()
            {
                Id = R.Id,
                RoleName=R.Name
               
            }).ToListAsync();
            return View(roles);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);
            return View(mappedRole);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task< IActionResult> Create(RoleViewModel roleVm)
        {
            if (ModelState.IsValid)
            {
                var roleMapped=_mapper.Map<RoleViewModel,IdentityRole>(roleVm);
                await _roleManager.CreateAsync(roleMapped);
                return RedirectToAction(nameof(Index));

            }
            return View(roleVm);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);
            return View(mappedRole);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel roleVm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    role.Name = roleVm.RoleName;
                    await _roleManager.UpdateAsync(role);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(roleVm);

        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);
            if (role == null)
            {
                return BadRequest();
            }
            return View(mappedRole);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, RoleViewModel roleVm)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(id);

                await _roleManager.DeleteAsync(role);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                var mappedRole = _mapper.Map<RoleViewModel, IdentityRole>(roleVm);
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(mappedRole);

            }
        }
    }

}

Welcome/Controllers/UserController.cs
using AutoMapper;
using Demo.DAl.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Welcome.Helpers;
using Welcome.ViewModels;

namespace Welcome.Controllers
{
    public class UserController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _mapper = mapper;
        }
        public  async Task<IActionResult> Index()
        {
            var users =await _userManager.Users.Select(U => new UserViewModel() 
            {
                Id = U.Id,
                FName=U.FName,
                LName=U.LName,
                PhoneNumber=U.PhoneNumber,
                Email=U.Email,
                Roles=_userManager.GetRolesAsync(U).Result
            }).ToListAsync();
            return View(users);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);
            return View(mappedUser);
        }
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);
            return View(mappedUser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel userVm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user= await _userManager.FindByIdAsync(id);
                    user.FName=userVm.FName;
                    user.LName=userVm.LName;
                    user.PhoneNumber=userVm.PhoneNumber;


                    await _userManager.UpdateAsync(user);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(userVm);

        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);
            if (user == null)
            {
                return BadRequest();
            }
            return View(mappedUser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, UserViewModel userVm)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);

                await _userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                var mappedEmp = _mapper.Map<UserViewModel, ApplicationUser>(userVm);
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(mappedEmp);

            }
        }
    }
}

Welcome/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome</title>
    <!-- Main css -->
    <link rel="stylesheet" href="~/css/AuthLayout.css">
</head>
<body>

    <div class="main">

        @RenderBody();
     

    </div>

    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
      <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

Welcome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Welcome</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/datatables/datatables.css" rel="stylesheet" />
    <link href="~/lib/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/css/status.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Welcome.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow justify-content-between mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class=" me-2 navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Signout">SignOut</a>
                    </li>
                </ul>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Welcome - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>